/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
} from "ethers";
import type {
  Listener,
  ContractEvent,
} from "../common";

export interface IntuitionVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "balances"
      | "deposit"
      | "isSweeper"
      | "owner"
      | "setSweeper"
      | "sweepTo"
      | "transferOwnership"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Deposited"
      | "OwnershipTransferred"
      | "SweeperUpdated"
      | "Swept"
      | "Withdrawn"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "balances",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "deposit", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isSweeper",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setSweeper",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "sweepTo",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "balances", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isSweeper", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setSweeper", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sweepTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace DepositedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = ContractEvent<InputTuple, OutputTuple, OutputObject>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = ContractEvent<InputTuple, OutputTuple, OutputObject>;
}

export namespace SweeperUpdatedEvent {
  export type InputTuple = [sweeper: AddressLike, allowed: boolean];
  export type OutputTuple = [sweeper: string, allowed: boolean];
  export interface OutputObject {
    sweeper: string;
    allowed: boolean;
  }
  export type Event = ContractEvent<InputTuple, OutputTuple, OutputObject>;
}

export namespace SweptEvent {
  export type InputTuple = [
    sweeper: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [sweeper: string, to: string, amount: bigint];
  export interface OutputObject {
    sweeper: string;
    to: string;
    amount: bigint;
  }
  export type Event = ContractEvent<InputTuple, OutputTuple, OutputObject>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = ContractEvent<InputTuple, OutputTuple, OutputObject>;
}

export interface IntuitionVault extends BaseContract {
  connect(runner?: ContractRunner | null): IntuitionVault;
  waitForDeployment(): Promise<this>;

  interface: IntuitionVaultInterface;

  queryFilter<TCEvent extends ContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<any>>;
  queryFilter<TCEvent extends ContractEvent>(
    filter: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<any>>;

  on<TCEvent extends ContractEvent>(
    event: TCEvent,
    listener: Listener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends ContractEvent>(
    filter: TCEvent,
    listener: Listener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends ContractEvent>(
    event: TCEvent,
    listener: Listener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends ContractEvent>(
    filter: TCEvent,
    listener: Listener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends ContractEvent>(
    event: TCEvent
  ): Promise<Array<Listener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends ContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  balances: ContractMethod<[arg0: AddressLike], [bigint], "view">;

  deposit: ContractMethod<[], [void], "payable">;

  isSweeper: ContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: ContractMethod<[], [string], "view">;

  setSweeper: ContractMethod<
    [sweeper: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  sweepTo: ContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: ContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdraw: ContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getFunction(nameOrSignature: "balances"): ContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(nameOrSignature: "deposit"): ContractMethod<[], [void], "payable">;
  getFunction(nameOrSignature: "isSweeper"): ContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(nameOrSignature: "owner"): ContractMethod<[], [string], "view">;
  getFunction(nameOrSignature: "setSweeper"): ContractMethod<[sweeper: AddressLike, allowed: boolean], [void], "nonpayable">;
  getFunction(nameOrSignature: "sweepTo"): ContractMethod<[to: AddressLike, amount: BigNumberish], [void], "nonpayable">;
  getFunction(nameOrSignature: "transferOwnership"): ContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(nameOrSignature: "withdraw"): ContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "Deposited"
  ): ContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): ContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SweeperUpdated"
  ): ContractEvent<
    SweeperUpdatedEvent.InputTuple,
    SweeperUpdatedEvent.OutputTuple,
    SweeperUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Swept"
  ): ContractEvent<
    SweptEvent.InputTuple,
    SweptEvent.OutputTuple,
    SweptEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): ContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "Deposited(address,uint256)": ContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: ContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": ContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: ContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SweeperUpdated(address,bool)": ContractEvent<
      SweeperUpdatedEvent.InputTuple,
      SweeperUpdatedEvent.OutputTuple,
      SweeperUpdatedEvent.OutputObject
    >;
    SweeperUpdated: ContractEvent<
      SweeperUpdatedEvent.InputTuple,
      SweeperUpdatedEvent.OutputTuple,
      SweeperUpdatedEvent.OutputObject
    >;

    "Swept(address,address,uint256)": ContractEvent<
      SweptEvent.InputTuple,
      SweptEvent.OutputTuple,
      SweptEvent.OutputObject
    >;
    Swept: ContractEvent<
      SweptEvent.InputTuple,
      SweptEvent.OutputTuple,
      SweptEvent.OutputObject
    >;

    "Withdrawn(address,uint256)": ContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: ContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
