/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IntuitionBettingOracle {
  export type EventDataStruct = {
    id: BigNumberish;
    question: string;
    description: string;
    category: string;
    imageUrl: string;
    bettingStopDate: BigNumberish;
    resolutionDate: BigNumberish;
    minStake: BigNumberish;
    maxStake: BigNumberish;
    yesPool: BigNumberish;
    noPool: BigNumberish;
    status: BigNumberish;
    winningOutcome: BigNumberish;
  };

  export type EventDataStructOutput = [
    id: bigint,
    question: string,
    description: string,
    category: string,
    imageUrl: string,
    bettingStopDate: bigint,
    resolutionDate: bigint,
    minStake: bigint,
    maxStake: bigint,
    yesPool: bigint,
    noPool: bigint,
    status: bigint,
    winningOutcome: bigint
  ] & {
    id: bigint;
    question: string;
    description: string;
    category: string;
    imageUrl: string;
    bettingStopDate: bigint;
    resolutionDate: bigint;
    minStake: bigint;
    maxStake: bigint;
    yesPool: bigint;
    noPool: bigint;
    status: bigint;
    winningOutcome: bigint;
  };

  export type BetStruct = {
    yesAmount: BigNumberish;
    noAmount: BigNumberish;
    claimed: boolean;
  };

  export type BetStructOutput = [
    yesAmount: bigint,
    noAmount: bigint,
    claimed: boolean
  ] & { yesAmount: bigint; noAmount: bigint; claimed: boolean };
}

export interface IntuitionBettingOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelEvent"
      | "claim"
      | "createEvent"
      | "events"
      | "getAllEventIds"
      | "getEvent"
      | "getMultipleUserBets"
      | "getUserBet"
      | "nextEventId"
      | "owner"
      | "placeBet"
      | "platformFeeBps"
      | "renounceOwnership"
      | "resolveEvent"
      | "setPlatformFee"
      | "setTreasury"
      | "transferOwnership"
      | "treasury"
      | "userBets"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BetPlaced"
      | "EventCanceled"
      | "EventCreated"
      | "EventResolved"
      | "OwnershipTransferred"
      | "WinningsClaimed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelEvent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "claim", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "createEvent",
    values: [
      string,
      string,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "events",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllEventIds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEvent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMultipleUserBets",
    values: [BigNumberish[], AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserBet",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextEventId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "placeBet",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "platformFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveEvent",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userBets",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "events", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllEventIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEvent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMultipleUserBets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getUserBet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextEventId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "placeBet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userBets", data: BytesLike): Result;
}

export namespace BetPlacedEvent {
  export type InputTuple = [
    eventId: BigNumberish,
    user: AddressLike,
    outcome: boolean,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    eventId: bigint,
    user: string,
    outcome: boolean,
    amount: bigint
  ];
  export interface OutputObject {
    eventId: bigint;
    user: string;
    outcome: boolean;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EventCanceledEvent {
  export type InputTuple = [eventId: BigNumberish];
  export type OutputTuple = [eventId: bigint];
  export interface OutputObject {
    eventId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EventCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    question: string,
    description: string,
    category: string,
    imageUrl: string,
    bettingStopDate: BigNumberish,
    resolutionDate: BigNumberish,
    minStake: BigNumberish,
    maxStake: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    question: string,
    description: string,
    category: string,
    imageUrl: string,
    bettingStopDate: bigint,
    resolutionDate: bigint,
    minStake: bigint,
    maxStake: bigint
  ];
  export interface OutputObject {
    id: bigint;
    question: string;
    description: string;
    category: string;
    imageUrl: string;
    bettingStopDate: bigint;
    resolutionDate: bigint;
    minStake: bigint;
    maxStake: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EventResolvedEvent {
  export type InputTuple = [
    eventId: BigNumberish,
    winningOutcome: BigNumberish
  ];
  export type OutputTuple = [eventId: bigint, winningOutcome: bigint];
  export interface OutputObject {
    eventId: bigint;
    winningOutcome: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinningsClaimedEvent {
  export type InputTuple = [
    eventId: BigNumberish,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [eventId: bigint, user: string, amount: bigint];
  export interface OutputObject {
    eventId: bigint;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IntuitionBettingOracle extends BaseContract {
  connect(runner?: ContractRunner | null): IntuitionBettingOracle;
  waitForDeployment(): Promise<this>;

  interface: IntuitionBettingOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelEvent: TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;

  claim: TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;

  createEvent: TypedContractMethod<
    [
      q: string,
      desc: string,
      cat: string,
      img: string,
      bettingStop: BigNumberish,
      resolution: BigNumberish,
      minStake: BigNumberish,
      maxStake: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  events: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        question: string;
        description: string;
        category: string;
        imageUrl: string;
        bettingStopDate: bigint;
        resolutionDate: bigint;
        minStake: bigint;
        maxStake: bigint;
        yesPool: bigint;
        noPool: bigint;
        status: bigint;
        winningOutcome: bigint;
      }
    ],
    "view"
  >;

  getAllEventIds: TypedContractMethod<[], [bigint[]], "view">;

  getEvent: TypedContractMethod<
    [id: BigNumberish],
    [IntuitionBettingOracle.EventDataStructOutput],
    "view"
  >;

  getMultipleUserBets: TypedContractMethod<
    [eventIds: BigNumberish[], user: AddressLike],
    [IntuitionBettingOracle.BetStructOutput[]],
    "view"
  >;

  getUserBet: TypedContractMethod<
    [eventId: BigNumberish, user: AddressLike],
    [IntuitionBettingOracle.BetStructOutput],
    "view"
  >;

  nextEventId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  placeBet: TypedContractMethod<
    [id: BigNumberish, outcome: boolean],
    [void],
    "payable"
  >;

  platformFeeBps: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resolveEvent: TypedContractMethod<
    [id: BigNumberish, yesWins: boolean],
    [void],
    "nonpayable"
  >;

  setPlatformFee: TypedContractMethod<
    [_newFeeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTreasury: TypedContractMethod<
    [_newTreasury: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  userBets: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [bigint, bigint, boolean] & {
        yesAmount: bigint;
        noAmount: bigint;
        claimed: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelEvent"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createEvent"
  ): TypedContractMethod<
    [
      q: string,
      desc: string,
      cat: string,
      img: string,
      bettingStop: BigNumberish,
      resolution: BigNumberish,
      minStake: BigNumberish,
      maxStake: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "events"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        question: string;
        description: string;
        category: string;
        imageUrl: string;
        bettingStopDate: bigint;
        resolutionDate: bigint;
        minStake: bigint;
        maxStake: bigint;
        yesPool: bigint;
        noPool: bigint;
        status: bigint;
        winningOutcome: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllEventIds"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getEvent"
  ): TypedContractMethod<
    [id: BigNumberish],
    [IntuitionBettingOracle.EventDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMultipleUserBets"
  ): TypedContractMethod<
    [eventIds: BigNumberish[], user: AddressLike],
    [IntuitionBettingOracle.BetStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserBet"
  ): TypedContractMethod<
    [eventId: BigNumberish, user: AddressLike],
    [IntuitionBettingOracle.BetStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextEventId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "placeBet"
  ): TypedContractMethod<
    [id: BigNumberish, outcome: boolean],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "platformFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveEvent"
  ): TypedContractMethod<
    [id: BigNumberish, yesWins: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPlatformFee"
  ): TypedContractMethod<[_newFeeBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[_newTreasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "userBets"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [bigint, bigint, boolean] & {
        yesAmount: bigint;
        noAmount: bigint;
        claimed: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "BetPlaced"
  ): TypedContractEvent<
    BetPlacedEvent.InputTuple,
    BetPlacedEvent.OutputTuple,
    BetPlacedEvent.OutputObject
  >;
  getEvent(
    key: "EventCanceled"
  ): TypedContractEvent<
    EventCanceledEvent.InputTuple,
    EventCanceledEvent.OutputTuple,
    EventCanceledEvent.OutputObject
  >;
  getEvent(
    key: "EventCreated"
  ): TypedContractEvent<
    EventCreatedEvent.InputTuple,
    EventCreatedEvent.OutputTuple,
    EventCreatedEvent.OutputObject
  >;
  getEvent(
    key: "EventResolved"
  ): TypedContractEvent<
    EventResolvedEvent.InputTuple,
    EventResolvedEvent.OutputTuple,
    EventResolvedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "WinningsClaimed"
  ): TypedContractEvent<
    WinningsClaimedEvent.InputTuple,
    WinningsClaimedEvent.OutputTuple,
    WinningsClaimedEvent.OutputObject
  >;

  filters: {
    "BetPlaced(uint256,address,bool,uint256)": TypedContractEvent<
      BetPlacedEvent.InputTuple,
      BetPlacedEvent.OutputTuple,
      BetPlacedEvent.OutputObject
    >;
    BetPlaced: TypedContractEvent<
      BetPlacedEvent.InputTuple,
      BetPlacedEvent.OutputTuple,
      BetPlacedEvent.OutputObject
    >;

    "EventCanceled(uint256)": TypedContractEvent<
      EventCanceledEvent.InputTuple,
      EventCanceledEvent.OutputTuple,
      EventCanceledEvent.OutputObject
    >;
    EventCanceled: TypedContractEvent<
      EventCanceledEvent.InputTuple,
      EventCanceledEvent.OutputTuple,
      EventCanceledEvent.OutputObject
    >;

    "EventCreated(uint256,string,string,string,string,uint256,uint256,uint256,uint256)": TypedContractEvent<
      EventCreatedEvent.InputTuple,
      EventCreatedEvent.OutputTuple,
      EventCreatedEvent.OutputObject
    >;
    EventCreated: TypedContractEvent<
      EventCreatedEvent.InputTuple,
      EventCreatedEvent.OutputTuple,
      EventCreatedEvent.OutputObject
    >;

    "EventResolved(uint256,uint8)": TypedContractEvent<
      EventResolvedEvent.InputTuple,
      EventResolvedEvent.OutputTuple,
      EventResolvedEvent.OutputObject
    >;
    EventResolved: TypedContractEvent<
      EventResolvedEvent.InputTuple,
      EventResolvedEvent.OutputTuple,
      EventResolvedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "WinningsClaimed(uint256,address,uint256)": TypedContractEvent<
      WinningsClaimedEvent.InputTuple,
      WinningsClaimedEvent.OutputTuple,
      WinningsClaimedEvent.OutputObject
    >;
    WinningsClaimed: TypedContractEvent<
      WinningsClaimedEvent.InputTuple,
      WinningsClaimedEvent.OutputTuple,
      WinningsClaimedEvent.OutputObject
    >;
  };
}
