/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
} from "ethers";
import type {
  Event,
  Listener,
  ContractEvent,
} from "../common";

export declare namespace IntuitionBettingOracle {
  export type EventDataStruct = {
    id: BigNumberish;
    question: string;
    description: string;
    category: string;
    imageUrl: string;
    bettingStopDate: BigNumberish;
    resolutionDate: BigNumberish;
    minStake: BigNumberish;
    maxStake: BigNumberish;
    yesPool: BigNumberish;
    noPool: BigNumberish;
    status: BigNumberish;
    winningOutcome: BigNumberish;
  };

  export type EventDataStructOutput = [
    id: bigint,
    question: string,
    description: string,
    category: string,
    imageUrl: string,
    bettingStopDate: bigint,
    resolutionDate: bigint,
    minStake: bigint,
    maxStake: bigint,
    yesPool: bigint,
    noPool: bigint,
    status: bigint,
    winningOutcome: bigint
  ] & {
    id: bigint;
    question: string;
    description: string;
    category: string;
    imageUrl: string;
    bettingStopDate: bigint;
    resolutionDate: bigint;
    minStake: bigint;
    maxStake: bigint;
    yesPool: bigint;
    noPool: bigint;
    status: bigint;
    winningOutcome: bigint;
  };

  export type BetStruct = {
    yesAmount: BigNumberish;
    noAmount: BigNumberish;
    claimed: boolean;
  };

  export type BetStructOutput = [
    yesAmount: bigint,
    noAmount: bigint,
    claimed: boolean
  ] & { yesAmount: bigint; noAmount: bigint; claimed: boolean };
}

export interface IntuitionBettingOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelEvent"
      | "claim"
      | "createEvent"
      | "events"
      | "getAllEventIds"
      | "getEvent"
      | "getMultipleUserBets"
      | "getUserBet"
      | "nextEventId"
      | "owner"
      | "placeBet"
      | "platformFeeBps"
      | "renounceOwnership"
      | "resolveEvent"
      | "setPlatformFee"
      | "setTreasury"
      | "transferOwnership"
      | "treasury"
      | "userBets"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BetPlaced"
      | "EventCanceled"
      | "EventCreated"
      | "EventResolved"
      | "OwnershipTransferred"
      | "WinningsClaimed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelEvent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "claim", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "createEvent",
    values: [
      string,
      string,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "events",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllEventIds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEvent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMultipleUserBets",
    values: [BigNumberish[], AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserBet",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextEventId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "placeBet",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "platformFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveEvent",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userBets",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "events", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllEventIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEvent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMultipleUserBets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getUserBet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextEventId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "placeBet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userBets", data: BytesLike): Result;
}

export namespace BetPlacedEvent {
  export type InputTuple = [
    eventId: BigNumberish,
    user: AddressLike,
    outcome: boolean,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    eventId: bigint,
    user: string,
    outcome: boolean,
    amount: bigint
  ];
  export interface OutputObject {
    eventId: bigint;
    user: string;
    outcome: boolean;
    amount: bigint;
  }
  export type Event = Event<InputTuple, OutputTuple, OutputObject>;
}

export namespace EventCanceledEvent {
  export type InputTuple = [eventId: BigNumberish];
  export type OutputTuple = [eventId: bigint];
  export interface OutputObject {
    eventId: bigint;
  }
  export type Event = Event<InputTuple, OutputTuple, OutputObject>;
}

export namespace EventCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    question: string,
    description: string,
    category: string,
    imageUrl: string,
    bettingStopDate: BigNumberish,
    resolutionDate: BigNumberish,
    minStake: BigNumberish,
    maxStake: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    question: string,
    description: string,
    category: string,
    imageUrl: string,
    bettingStopDate: bigint,
    resolutionDate: bigint,
    minStake: bigint,
    maxStake: bigint
  ];
  export interface OutputObject {
    id: bigint;
    question: string;
    description: string;
    category: string;
    imageUrl: string;
    bettingStopDate: bigint;
    resolutionDate: bigint;
    minStake: bigint;
    maxStake: bigint;
  }
  export type Event = Event<InputTuple, OutputTuple, OutputObject>;
}

export namespace EventResolvedEvent {
  export type InputTuple = [
    eventId: BigNumberish,
    winningOutcome: BigNumberish
  ];
  export type OutputTuple = [eventId: bigint, winningOutcome: bigint];
  export interface OutputObject {
    eventId: bigint;
    winningOutcome: bigint;
  }
  export type Event = Event<InputTuple, OutputTuple, OutputObject>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = Event<InputTuple, OutputTuple, OutputObject>;
}

export namespace WinningsClaimedEvent {
  export type InputTuple = [
    eventId: BigNumberish,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [eventId: bigint, user: string, amount: bigint];
  export interface OutputObject {
    eventId: bigint;
    user: string;
    amount: bigint;
  }
  export type Event = Event<InputTuple, OutputTuple, OutputObject>;
}

export interface IntuitionBettingOracle extends BaseContract {
  connect(runner?: ContractRunner | null): IntuitionBettingOracle;
  waitForDeployment(): Promise<this>;

  interface: IntuitionBettingOracleInterface;

  queryFilter<TCEvent extends ContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<any>>;
  queryFilter<TCEvent extends ContractEvent>(
    filter: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<any>>;

  on<TCEvent extends ContractEvent>(
    event: TCEvent,
    listener: Listener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends ContractEvent>(
    filter: TCEvent,
    listener: Listener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends ContractEvent>(
    event: TCEvent,
    listener: Listener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends ContractEvent>(
    filter: TCEvent,
    listener: Listener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends ContractEvent>(
    event: TCEvent
  ): Promise<Array<Listener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends ContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelEvent: ContractMethod<[id: BigNumberish], [void], "nonpayable">;

  claim: ContractMethod<[id: BigNumberish], [void], "nonpayable">;

  createEvent: ContractMethod<
    [
      q: string,
      desc: string,
      cat: string,
      img: string,
      bettingStop: BigNumberish,
      resolution: BigNumberish,
      minStake: BigNumberish,
      maxStake: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  events: ContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        question: string;
        description: string;
        category: string;
        imageUrl: string;
        bettingStopDate: bigint;
        resolutionDate: bigint;
        minStake: bigint;
        maxStake: bigint;
        yesPool: bigint;
        noPool: bigint;
        status: bigint;
        winningOutcome: bigint;
      }
    ],
    "view"
  >;

  getAllEventIds: ContractMethod<[], [bigint[]], "view">;

  getEvent: ContractMethod<
    [id: BigNumberish],
    [IntuitionBettingOracle.EventDataStructOutput],
    "view"
  >;

  getMultipleUserBets: ContractMethod<
    [eventIds: BigNumberish[], user: AddressLike],
    [IntuitionBettingOracle.BetStructOutput[]],
    "view"
  >;

  getUserBet: ContractMethod<
    [eventId: BigNumberish, user: AddressLike],
    [IntuitionBettingOracle.BetStructOutput],
    "view"
  >;

  nextEventId: ContractMethod<[], [bigint], "view">;

  owner: ContractMethod<[], [string], "view">;

  placeBet: ContractMethod<
    [id: BigNumberish, outcome: boolean],
    [void],
    "payable"
  >;

  platformFeeBps: ContractMethod<[], [bigint], "view">;

  renounceOwnership: ContractMethod<[], [void], "nonpayable">;

  resolveEvent: ContractMethod<
    [id: BigNumberish, yesWins: boolean],
    [void],
    "nonpayable"
  >;

  setPlatformFee: ContractMethod<
    [_newFeeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTreasury: ContractMethod<
    [_newTreasury: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: ContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: ContractMethod<[], [string], "view">;

  userBets: ContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [bigint, bigint, boolean] & {
        yesAmount: bigint;
        noAmount: bigint;
        claimed: boolean;
      }
    ],
    "view"
  >;

  getFunction(nameOrSignature: "cancelEvent"): ContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(nameOrSignature: "claim"): ContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(nameOrSignature: "createEvent"): ContractMethod<[q: string, desc: string, cat: string, img: string, bettingStop: BigNumberish, resolution: BigNumberish, minStake: BigNumberish, maxStake: BigNumberish], [void], "nonpayable">;
  getFunction(nameOrSignature: "events"): ContractMethod<[arg0: BigNumberish], [[ bigint, string, string, string, string, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint ] & { id: bigint; question: string; description: string; category: string; imageUrl: string; bettingStopDate: bigint; resolutionDate: bigint; minStake: bigint; maxStake: bigint; yesPool: bigint; noPool: bigint; status: bigint; winningOutcome: bigint; }], "view">;
  getFunction(nameOrSignature: "getAllEventIds"): ContractMethod<[], [bigint[]], "view">;
  getFunction(nameOrSignature: "getEvent"): ContractMethod<[id: BigNumberish], [IntuitionBettingOracle.EventDataStructOutput], "view">;
  getFunction(nameOrSignature: "getMultipleUserBets"): ContractMethod<[eventIds: BigNumberish[], user: AddressLike], [IntuitionBettingOracle.BetStructOutput[]], "view">;
  getFunction(nameOrSignature: "getUserBet"): ContractMethod<[eventId: BigNumberish, user: AddressLike], [IntuitionBettingOracle.BetStructOutput], "view">;
  getFunction(nameOrSignature: "nextEventId"): ContractMethod<[], [bigint], "view">;
  getFunction(nameOrSignature: "owner"): ContractMethod<[], [string], "view">;
  getFunction(nameOrSignature: "placeBet"): ContractMethod<[id: BigNumberish, outcome: boolean], [void], "payable">;
  getFunction(nameOrSignature: "platformFeeBps"): ContractMethod<[], [bigint], "view">;
  getFunction(nameOrSignature: "renounceOwnership"): ContractMethod<[], [void], "nonpayable">;
  getFunction(nameOrSignature: "resolveEvent"): ContractMethod<[id: BigNumberish, yesWins: boolean], [void], "nonpayable">;
  getFunction(nameOrSignature: "setPlatformFee"): ContractMethod<[_newFeeBps: BigNumberish], [void], "nonpayable">;
  getFunction(nameOrSignature: "setTreasury"): ContractMethod<[_newTreasury: AddressLike], [void], "nonpayable">;
  getFunction(nameOrSignature: "transferOwnership"): ContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(nameOrSignature: "treasury"): ContractMethod<[], [string], "view">;
  getFunction(nameOrSignature: "userBets"): ContractMethod<[arg0: BigNumberish, arg1: AddressLike], [[bigint, bigint, boolean] & { yesAmount: bigint; noAmount: bigint; claimed: boolean; }], "view">;

  getEvent(
    key: "BetPlaced"
  ): ContractEvent<
    BetPlacedEvent.InputTuple,
    BetPlacedEvent.OutputTuple,
    BetPlacedEvent.OutputObject
  >;
  getEvent(
    key: "EventCanceled"
  ): ContractEvent<
    EventCanceledEvent.InputTuple,
    EventCanceledEvent.OutputTuple,
    EventCanceledEvent.OutputObject
  >;
  getEvent(
    key: "EventCreated"
  ): ContractEvent<
    EventCreatedEvent.InputTuple,
    EventCreatedEvent.OutputTuple,
    EventCreatedEvent.OutputObject
  >;
  getEvent(
    key: "EventResolved"
  ): ContractEvent<
    EventResolvedEvent.InputTuple,
    EventResolvedEvent.OutputTuple,
    EventResolvedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): ContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "WinningsClaimed"
  ): ContractEvent<
    WinningsClaimedEvent.InputTuple,
    WinningsClaimedEvent.OutputTuple,
    WinningsClaimedEvent.OutputObject
  >;

  filters: {
    "BetPlaced(uint256,address,bool,uint256)": ContractEvent<
      BetPlacedEvent.InputTuple,
      BetPlacedEvent.OutputTuple,
      BetPlacedEvent.OutputObject
    >;
    BetPlaced: ContractEvent<
      BetPlacedEvent.InputTuple,
      BetPlacedEvent.OutputTuple,
      BetPlacedEvent.OutputObject
    >;

    "EventCanceled(uint256)": ContractEvent<
      EventCanceledEvent.InputTuple,
      EventCanceledEvent.OutputTuple,
      EventCanceledEvent.OutputObject
    >;
    EventCanceled: ContractEvent<
      EventCanceledEvent.InputTuple,
      EventCanceledEvent.OutputTuple,
      EventCanceledEvent.OutputObject
    >;

    "EventCreated(uint256,string,string,string,string,uint256,uint256,uint256,uint256)": ContractEvent<
      EventCreatedEvent.InputTuple,
      EventCreatedEvent.OutputTuple,
      EventCreatedEvent.OutputObject
    >;
    EventCreated: ContractEvent<
      EventCreatedEvent.InputTuple,
      EventCreatedEvent.OutputTuple,
      EventCreatedEvent.OutputObject
    >;

    "EventResolved(uint256,uint8)": ContractEvent<
      EventResolvedEvent.InputTuple,
      EventResolvedEvent.OutputTuple,
      EventResolvedEvent.OutputObject
    >;
    EventResolved: ContractEvent<
      EventResolvedEvent.InputTuple,
      EventResolvedEvent.OutputTuple,
      EventResolvedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": ContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: ContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "WinningsClaimed(uint256,address,uint256)": ContractEvent<
      WinningsClaimedEvent.InputTuple,
      WinningsClaimedEvent.OutputTuple,
      WinningsClaimedEvent.OutputObject
    >;
    WinningsClaimed: ContractEvent<
      WinningsClaimedEvent.InputTuple,
      WinningsClaimedEvent.OutputTuple,
      WinningsClaimedEvent.OutputObject
    >;
  };
}
