/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  FunctionFragment,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  ContractEvent,
  EventLog,
  Listener as TypedListener,
} from "../../../common";

export interface ReentrancyGuardInterface extends Interface {}

export interface ReentrancyGuard extends BaseContract {
  connect(runner?: ContractRunner | null): ReentrancyGuard;
  waitForDeployment(): Promise<this>;

  interface: ReentrancyGuardInterface;

  queryFilter<TCEvent extends ContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<EventLog<TCEvent>>>;
  queryFilter<TCEvent extends ContractEvent>(
    filter: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<EventLog<TCEvent>>>;

  on<TCEvent extends ContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends ContractEvent>(
    filter: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends ContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends ContractEvent>(
    filter: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends ContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends ContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  filters: {};
}
