/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  FunctionFragment,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  ContractEvent,
} from "../../../common";

export interface ShortStringsInterface extends Interface {}

export interface ShortStrings extends BaseContract {
  connect(runner?: ContractRunner | null): ShortStrings;
  waitForDeployment(): Promise<this>;

  interface: ShortStringsInterface;

  queryFilter<TCEvent extends ContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<any>>;
  queryFilter<TCEvent extends ContractEvent>(
    filter: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<any>>;

  on<TCEvent extends ContractEvent>(
    event: TCEvent,
    listener: Listener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends ContractEvent>(
    filter: TCEvent,
    listener: Listener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends ContractEvent>(
    event: TCEvent,
    listener: Listener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends ContractEvent>(
    filter: TCEvent,
    listener: Listener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends ContractEvent>(
    event: TCEvent
  ): Promise<Array<Listener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends ContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  filters: {};
}
