/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
} from "ethers";
import type {
  Listener,
  ContractEvent,
} from "../../../../common";

export interface EIP712Interface extends Interface {
  getFunction(nameOrSignature: "eip712Domain"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "EIP712DomainChanged"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = ContractEvent<InputTuple, OutputTuple, OutputObject>;
}

export interface EIP712 extends BaseContract {
  connect(runner?: ContractRunner | null): EIP712;
  waitForDeployment(): Promise<this>;

  interface: EIP712Interface;

  queryFilter<TCEvent extends ContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<any>>;
  queryFilter<TCEvent extends ContractEvent>(
    filter: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<any>>;

  on<TCEvent extends ContractEvent>(
    event: TCEvent,
    listener: Listener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends ContractEvent>(
    filter: TCEvent,
    listener: Listener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends ContractEvent>(
    event: TCEvent,
    listener: Listener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends ContractEvent>(
    filter: TCEvent,
    listener: Listener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends ContractEvent>(
    event: TCEvent
  ): Promise<Array<Listener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends ContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  eip712Domain: ContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "eip712Domain"
  ): ContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  getEvent(
    key: "EIP712DomainChanged"
  ): ContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >;

  filters: {
    "EIP712DomainChanged()": ContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
    EIP712DomainChanged: ContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
  };
}
