/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
} from "ethers";
import type {
  Listener,
  ContractEvent,
} from "../../../common";

export interface OwnableInterface extends Interface {
  getFunction(
    nameOrSignature: "owner" | "renounceOwnership" | "transferOwnership"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): FunctionFragment;

  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = ContractEvent<InputTuple, OutputTuple, OutputObject>;
}

export interface Ownable extends BaseContract {
  connect(runner?: ContractRunner | null): Ownable;
  waitForDeployment(): Promise<this>;

  interface: OwnableInterface;

  queryFilter<TCEvent extends ContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<any>>;
  queryFilter<TCEvent extends ContractEvent>(
    filter: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<any>>;

  on<TCEvent extends ContractEvent>(
    event: TCEvent,
    listener: Listener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends ContractEvent>(
    filter: TCEvent,
    listener: Listener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends ContractEvent>(
    event: TCEvent,
    listener: Listener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends ContractEvent>(
    filter: TCEvent,
    listener: Listener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends ContractEvent>(
    event: TCEvent
  ): Promise<Array<Listener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends ContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  owner: ContractMethod<[], [string], "view">;

  renounceOwnership: ContractMethod<[], [void], "nonpayable">;

  transferOwnership: ContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "owner"
  ): ContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): ContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): ContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): ContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": ContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: ContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
