/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  EventFragment,
  FunctionFragment,
  Result,
  Interface,
  Listener,
} from "ethers";
import type {
  ContractTransaction,
  ContractTransactionResponse,
  ContractMethod,
} from "ethers";

export type EventLog = {
  topics: readonly string[];
  data: string;
  transactionHash: string;
  blockHash: string;
  blockNumber: number;
  transactionIndex: number;
  logIndex: number;
  address: string;
};

export interface Event<TArgs extends any[] = any[], TObject = any> {
  readonly args: TArgs & TObject;
  readonly eventName: string;
  readonly signature: string;

  log: EventLog;
  removeListener: () => Promise<this>;
  getTransaction: () => Promise<ContractTransactionResponse>;
  getTransactionReceipt: () => Promise<import("ethers").TransactionReceipt | null>;
}

export type Listener<T extends Event> = (
  ...listenerArg: [...T["args"], T]
) => void;

export type ContractEvent<T extends Event> = {
  listeners<U extends T>(eventName?: U["eventName"]): Promise<Array<Listener<U>>>;
  off<U extends T>(event: U, listener: Listener<U>): Promise<this>;
  on<U extends T>(event: U, listener: Listener<U>): Promise<this>;
  once<U extends T>(event: U, listener: Listener<U>): Promise<this>;
  removeListener<U extends T>(event: U, listener: Listener<U>): Promise<this>;
};
