/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  EventFragment,
  FunctionFragment,
  ContractTransactionResponse,
  BaseContract,
  Result,
  Interface,
  ContractTransaction,
  ContractMethod,
  Listener,
} from "ethers";

export type EventLog = {
  topics: readonly string[];
  data: string;
  transactionHash: string;
  blockHash: string;
  blockNumber: number;
  transactionIndex: number;
  logIndex: number;
  address: string;
};

export interface TypedEventLog<T extends TypedEvent> extends EventLog {
  args: T["args"];
}

export type TypedListener<T extends TypedEvent> = (
  ...listenerArg: [...T["args"], TypedEventLog<T>]
) => void;

export type TypedEvent<
  TArgsArray extends any[] = any[],
  TArgsObject = any
> = {
  readonly name: string;
  readonly signature: string;
  readonly args: TArgsArray & TArgsObject;
};

export interface ContractEvent<
  T extends TypedEvent,
  TName extends string = string
> {
  (...args: T["args"]): string;
  name: TName;
  fragment: EventFragment;
  getFragment(...args: T["args"]): EventFragment;
}
