/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  EventFragment,
  FunctionFragment,
  Result,
  Interface,
  Listener,
  AddressLike,
  BytesLike,
  BigNumberish,
  ContractRunner,
  ContractMethod,
  ContractTransaction,
  ContractTransactionResponse,
} from "ethers";

export type EventLog = {
  topics: readonly string[];
  data: string;
  transactionHash: string;
  blockHash: string;
  blockNumber: number;
  transactionIndex: number;
  logIndex: number;
  address: string;
};

export interface ContractEvent<
  TInput extends any[] = any[],
  TOutput extends any[] | object = any[],
  TOutputObject = TOutput extends any[] ? any : TOutput
> {
  (...args: TOutput): ContractEvent<TInput, TOutput, TOutputObject>;
  getFragment(
    ...args: TInput
  ): EventFragment;
}

export type Listener<T extends ContractEvent> = (
  ...listenerArg: [
    ...Parameters<T>,
    {
      args: Parameters<T>;
      log: EventLog;
      removeListener: () => Promise<void>;
      getTransaction: () => Promise<ContractTransactionResponse>;
      getTransactionReceipt: () => Promise<import("ethers").TransactionReceipt | null>;
    }
  ]
) => void;
